stages:
  - build
  - deploy

# Stage Build: Build dan push Docker image ke Docker Hub
build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

# Stage Deploy: SSH ke VPS dan jalankan Docker container dengan docker-compose.prod.yml
deploy_to_vps:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
  script:
    - echo "Deploying to VPS..."
    - ssh -o StrictHostKeyChecking=no -i id_rsa $VPS_USER_HOST "
        echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin &&
        docker pull $DOCKER_IMAGE:latest &&
        docker stop payment-options || true &&
        docker rm payment-options || true &&
        docker-compose -f docker-compose.prod.yml up -d"
  only:
    - main
